spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  aws-s3:
    accessKey: AKIATZNO6JSWPOZR2G6S
    secretKey: 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
    bucket: bucketprodutoyoutubr